### ISSUE TITLE
The 1.1.13 release didn't publish artifacts for Scala 2.10 (sbt 0.13)

### ISSUE THREAD

**Issue by ennru** [playframework/play-file-watch#100]
In the build make-over I dropped the Scala 2.10 cross-building which is required for use in sbt 0.13.

https://github.com/playframework/play-file-watch/compare/1.1.12...1.1.13

If anybody is interested, please suggest a PR to bring Scala 2.10 back and I'll cut a new release.

**Comment by ignasi35** [comment]
I think the change was https://github.com/playframework/play-file-watch/commit/fab480855316b9025aa584f795bdb5ea93a2a775
