### ISSUE TITLE
`better-files` should have Scala 3 artifact soon (hopefully)

### ISSUE THREAD

**Issue by mkurz** [playframework/play-file-watch#200]
https://github.com/playframework/play-file-watch/blob/a2b4e3b9b529bbe722019bd8ec3f74d544834edb/build.sbt#L30

PR was merged already a couple of days ago: https://github.com/pathikrit/better-files/pull/573

Just a reminder because the repo does not publish GitHub releases I can subscribe to.

**Comment by pathikrit** [comment]
Ok I think I finally managed to release v3.9.2 for Scala 3: 
https://github.com/pathikrit/better-files/actions/runs/4117102133/jobs/7107991092#step:7:330

Please confirm usage!

**Comment by mkurz** [comment]
@pathikrit Thanks, will try asap when artifacts are published, still waiting: https://repo1.maven.org/maven2/com/github/pathikrit/

BTW: You didn't push the 4.0.0 tag: https://github.com/pathikrit/better-files/tags

**Comment by mkurz** [comment]
Ah, sorry it's 3.92, the title of the workflow mentiones 4.0.0 already, so I was confused.

**Comment by mkurz** [comment]
@pathikrit looks good: #201, thanks!
