### ISSUE TITLE
Drop Scala 2.10 support

### ISSUE THREAD

**Issue by raboof** [playframework/play-file-watch#28]
Tricky to maintain because of (likely among other things) there is no version of better-files that supports Scala 2.10 through 2.13

**Comment by raboof** [comment]
We want to postpone this until Play 2.7 is out (including for Scala 2.13), see also https://github.com/playframework/playframework/issues/8959

**Comment by dwijnand** [comment]
Yeah, this can't happen before playframework/playframework#8959 (though they can happen at the same time! 😉)
